### PR TITLE
fix: Update wave args of ui.time_picker on every time change #1889

### LINKED ISSUE #1889: Visuals of time_picker selection don't always match passed argument
### Discussed in https://github.com/h2oai/wave/discussions/1888

<div type='discussions-op-text'>

<sup>Originally posted by **aranvir** March 14, 2023</sup>
Hi! First of all, I really enjoy working with this framework and exploring this.

I found an issue that can be best reproduced with the time_picker https://wave.h2o.ai/docs/examples/time-picker

When selecting the required time, one needs to explicitly click on the the hour and the minutes to set a proper time. If, for example, you just click on 12 (which auto-completes to 12:00) and then click on the white space around, the value will be displayed BUT when you click Submit, the time passed is actually `None`.

So this is of course a bit counter-intuitive because you see the time you wanted to enter, but it is then not actually set. I assume the same will happen for other "multi-stage" pickers where implicit values are not considered a confirmation of the form input, but I haven't tested it.

Not sure, if this can be solved programmatically or if this is just "how forms work". If it's the latter then I think this is something that should be mentioned in the documentation so frontend noobs like me are not caught by surprise ;)</div>

via @aranvir

### PR DESCRIPTION
**Pull request by marek-mihok**
Updating of wave args if now moved from time picker's `onAccept` to `onChange` to make sure it is updated every time user changes the time, not only on popup close.

Closes #1889

### CODE REVIEW

File: ui/src/time_picker.tsx [hunk 1]
```diff
@@ -212,8 +213,8 @@ export const
                 value={value}
                 label={label}
                 open={isDialogOpen}
-                onChange={value => setValue(value as Date)}
-                onAccept={value => onSelectTime(value as Date)}
+                onChange={value => onChangeTime(value as Date)}
```
Comment (mturoci) [inline ui/src/time_picker.tsx:216]: Let's use proper types here.

```suggestion
                onChange={onChangeTime}
```

**Review by mturoci — CHANGES_REQUESTED** [review]
Thanks @marek-mihok. The fix looks correct. Please add unit tests as well.

File: ui/src/time_picker.tsx (hunk 1 above)
Comment (marek-mihok) [reply ui/src/time_picker.tsx:216]: What do you mean by proper types? onChange gives us the value of type `unknown`, which is basically a Date object every time. Do you mean I should replace the param type in my `onChangeTime` handler with `unknown`? 

```ts
- onChangeTime = (time: D | null) => {
+ onChangeTime = (time: unknown) => {
```

Comment (mturoci) [reply ui/src/time_picker.tsx:216]: >onChange gives us the value of type unknown, which is basically a Date object every time

If it were true, it wouldn't be typed as unknown, but Date.

>Do you mean I should replace the param type in my onChangeTime handler with unknown?

The current `onChangeTime` function signature doesn't match the one in the lib. In addition to the value, there is also `keyboardInputValue` which I assume allows for selecting time with a keyboard as well so would be good to support that also.

Comment (marek-mihok) [reply ui/src/time_picker.tsx:216]: > I assume allows for selecting time with a keyboard as well so would be good to support that also

IIRC the keyboard input was supported during development of this component but in later phases we agreed on removing the support. I can't remember the specific reason, but I think there were a lot of edge cases to handle and the code was too robust. Also we wanted to make it consistent with a date picker where you cannot use keyboard input as well. You can pick only what the picker offers you to select and also you don't need to care about formats (should I write `04:00`, `4:00`, `4:00 am` or `4:00am`?).

However, If you want to support it, I can create a feature request and/or add there a TODO.

Comment (mturoci) [reply ui/src/time_picker.tsx:216]: Ah, I remember now, fair point. Let's leave it as is then and handle only the `unknown` part of my prev comment.

**Comment by marek-mihok** [comment]
@mturoci regarding unit tests there is no easy way of triggering click events on the clock component. That's why we have only tests which exclude time change using the clock picker. That means having tests where `onChange` is called (where `wave.args` are set) can be problematic. The question is if we want to spend a long time efforts (as the last time) trying to create these tests without a guaranteed success.

**Review by mturoci — APPROVED** [review]
The test you added is enough as it fails without this fix. Good job!
