### PR TITLE
fix: API section of the docs has mismatched sidebar and index items

### LINKED ISSUE #455: API section of the docs has mismatched sidebar and index items
- This page https://h2oai.github.io/wave/docs/api/index lists some modules that are not released yet.
- The sidebar only shows released modules.

### PR DESCRIPTION
**Pull request by srini-x**
fixes #455 

- [x] added `__pdoc__` dict to `py/h2o_wave/__init__.py` to ignore unreleased submodules. Relevant [pdoc3 documentation](https://pdoc3.github.io/pdoc/doc/pdoc/#overriding-docstrings-with-__pdoc__)
- [x] Fixed the order of topics in the sidebar to match the api index page.

### CODE REVIEW

**Review by lo5 — APPROVED** [review]
Thanks @srini-x!

File: website/sidebars.js [hunk 1]
```diff
@@ -55,11 +55,11 @@ module.exports = {
     'API': [
       'api/index',
       'api/core',
-      'api/ui',
-      'api/server',
       'api/graphics',
-      'api/types',
+      'api/server',
```
Comment (lo5) [inline website/sidebars.js:59]: I'd prefer to preserve the original order for the sidebar - they're arranged from most-relevant to least-relevant.

**Review by lo5 — CHANGES_REQUESTED** [review]
I spoke too soon - it would be good to preserve the original order in the sidebar.

File: website/sidebars.js (hunk 1 above)
Comment (srini-x) [reply website/sidebars.js:59]: suspected that. they looked purposefully arranged. fixing...

Comment (srini-x) [reply website/sidebars.js:59]: @lo5, shall I add `ui_ext` under `ui` like this?

```js
    'API': [
      'api/index',
      'api/core',
      'api/ui',
      'api/ui_ext',
      'api/server',
      'api/graphics',
      'api/types',
      'api/test',
    ],
```

Comment (lo5) [reply website/sidebars.js:59]: Yes, sounds good.

Comment (srini-x) [reply website/sidebars.js:60]: done!

**Review by lo5 — APPROVED** [review]
Thanks @srini-x!
