### PR TITLE
fix: Add support to dynamically change Dropdown value

### LINKED ISSUE #1574: Dropdown value clearing
#### Wave SDK Version, OS

0.21.1

#### Actual behavior

I have two dropdowns and I need to clear the selected value of the second dropdown when the value of the first dropdown changes. 

This works fine with form by setting the second dropdown value as `None`.

```python
from h2o_wave import app, main, Q, ui


@app("/")
async def serve(q: Q) -> None:
    if q.args.dropdown1:
        if q.args.dropdown1 != q.client.dropdown1:
            q.client.dropdown1_changed = True
        else:
            q.client.dropdown1_changed = False
        q.client.dropdown1 = q.args.dropdown1
    if q.args.dropdown2:
        if q.client.dropdown1_changed:
            q.client.dropdown2 = None
        else:
            q.client.dropdown2 = q.args.dropdown2

    q.page["example"] = ui.form_card(
        box="1 1 2 2",
        items=[
            ui.dropdown(
                name="dropdown1",
                label="Dropdown1",
                value=q.client.dropdown1,
                trigger=True,
                choices=[
                    ui.choice(name="1", label="Choice 1"),
                    ui.choice(name="2", label="Choice 2"),
                    ui.choice(name="3", label="Choice 3"),
                ],
            ),
            ui.dropdown(
                name="dropdown2",
                label="Dropdown2",
                value=q.client.dropdown2,
                trigger=True,
                choices=[
                    ui.choice(name="a", label="Choice a"),
                    ui.choice(name="b", label="Choice b"),
                    ui.choice(name="c", label="Choice c"),
                ],
            ),
        ],
    )

    await q.page.save()
```

https://user-images.githubusercontent.com/29954570/183110581-37e9c894-6e90-415c-9391-51fdd2db78c3.mov

When the dropdowns are in a side panel, you need to set the value of the second dropdown as a value except `None`.

Scenario 1: Value as `None` - Not working.

``` python
from h2o_wave import app, main, Q, ui

@app("/")
async def serve(q: Q) -> None:
    if not q.client.initialized:
        q.page['meta'] = ui.meta_card(box='')
        q.page['example'] = ui.form_card(box='1 1 2 1', items=[
            ui.button(name='show_side_panel', label='Open side panel', primary=True)
        ])
        q.client.initialized = True
    else:
        if q.args.show_side_panel:
            show_side_panel(q)

        if q.args.dropdown1:
            if q.args.dropdown1 != q.client.dropdown1:
                q.client.dropdown2 = None
            q.client.dropdown1 = q.args.dropdown1
            show_side_panel(q)
        if q.args.dropdown2:
            q.client.dropdown2 = q.args.dropdown2
            show_side_panel(q)
        if q.args.cancel:
            q.page['meta'].side_panel = None
            q.client.dropdown1 = None
            q.client.dropdown2 = None

    await q.page.save()


def show_side_panel(q):
    q.page["meta"].side_panel = ui.side_panel(
        title="Side Panel",
        items=[
            ui.dropdown(
                name="dropdown1",
                label="Dropdown1",
                value=q.client.dropdown1,
                trigger=True,
                choices=[
                    ui.choice(name="1", label="Choice 1"),
                    ui.choice(name="2", label="Choice 2"),
                    ui.choice(name="3", label="Choice 3"),
                ],
            ),
            ui.dropdown(
                name="dropdown2",
                label="Dropdown2",
                value=q.client.dropdown2,
                trigger=True,
                choices=[
                    ui.choice(name="a", label="Choice a"),
                    ui.choice(name="b", label="Choice b"),
                    ui.choice(name="c", label="Choice c"),
                ],
            ),
            ui.button(name='cancel', label='Cancel')
        ],
        events=["dismissed"],
        closable=True,
    )
```

https://user-images.githubusercontent.com/29954570/183111407-bde3cb22-b764-495d-91f4-e2fb001288b4.mov

Scenario 2: Value as an empty string - working.

```  python
from h2o_wave import app, main, Q, ui

@app("/")
async def serve(q: Q) -> None:
    if not q.client.initialized:
        q.page['meta'] = ui.meta_card(box='')
        q.page['example'] = ui.form_card(box='1 1 2 1', items=[
            ui.button(name='show_side_panel', label='Open side panel', primary=True)
        ])
        q.client.initialized = True
    else:
        if q.args.show_side_panel:
            show_side_panel(q)

        if q.args.dropdown1:
            if q.args.dropdown1 != q.client.dropdown1:
                q.client.dropdown2 = ""
            q.client.dropdown1 = q.args.dropdown1
            show_side_panel(q)
        if q.args.dropdown2:
            q.client.dropdown2 = q.args.dropdown2
            show_side_panel(q)
        if q.args.cancel:
            q.page['meta'].side_panel = None
            q.client.dropdown1 = None
            q.client.dropdown2 = None

    await q.page.save()


def show_side_panel(q):
    q.page["meta"].side_panel = ui.side_panel(
        title="Side Panel",
        items=[
            ui.dropdown(
                name="dropdown1",
                label="Dropdown1",
                value=q.client.dropdown1,
                trigger=True,
                choices=[
                    ui.choice(name="1", label="Choice 1"),
                    ui.choice(name="2", label="Choice 2"),
                    ui.choice(name="3", label="Choice 3"),
                ],
            ),
            ui.dropdown(
                name="dropdown2",
                label="Dropdown2",
                value=q.client.dropdown2,
                trigger=True,
                choices=[
                    ui.choice(name="a", label="Choice a"),
                    ui.choice(name="b", label="Choice b"),
                    ui.choice(name="c", label="Choice c"),
                ],
            ),
            ui.button(name='cancel', label='Cancel')
        ],
        events=["dismissed"],
        closable=True,
    )
```

https://user-images.githubusercontent.com/29954570/183111658-97f40304-f07e-4fd1-85d2-bd9cfed24ace.mov

#### Expected behavior

Expect to clear the value of a dropdown in a side panel, when it is set as `None`.

### PR DESCRIPTION
**Pull request by aalencar**
## Multi-valued dialog Dropdown Refactor notes

On line 189, since `filteredItems` is intialized with `items`, `setFilteredItems` was mutating `items` when it set `i.checked = checked` which is definitely an antipattern, plus `items` uses `useMemo` which should only change when its dependencies change.
`189: selectAll = (checked = true) => () => setFilteredItems(filteredItems.map(i => { i.checked = checked; return i })),`

`filteredItems` should represent the displayed items and should rely on `items` as single source of truth. The refactoring makes it so that we change `items` and the changes are reflected to `filteredItem` through `useEffect`. Same for searching.

 I believe this is a better mental model.

## Unrelated bugs

I fixed a bug where multi-valued dialog Dropdown was setting wave args to string when it only had a single value selected and it was setting wave args to array for more than one value. Now it's always an array. No one has reported this issue but if they handled this in their code, the fix might break it.

## Performance concerns

We are using `toString()` to compare array content and it can be an expensive computation.

I tested dialog with 100k options and it was fine.

## Updating `choices` prop

This PR solves the issue which was concerned about changing `value` and `values`. Updating `choices` dynamically could be done in a separate PR due to the number of changes and complexity already present in this one.

## Further improvements

The code is still quite complex. We could split each component into single-valued and multi-valued like we did for dropdown. Maybe it would be easier to follow.

Any suggestion is welcomed.

## Handy repro code

```py
from h2o_wave import app, main, Q, ui

combobox_choices = ['A', 'B', 'C']

@app("/demo")
async def serve(q: Q) -> None:
    if not q.client.initialized:
        q.client.initialized = True
        q.page["example"] = ui.form_card(
            box="1 1 4 6",
            items=[
                ui.dropdown(
                    name='dp1',
                    label='base single',
                    choices=[
                        ui.choice(name="a", label="choice a"),
                        ui.choice(name="b", label="choice b"),
                        ui.choice(name="c", label="choice c"),
                    ],
                    value="a",
                ),
                 ui.dropdown(
                    name='dp2',
                    label='base multi',
                    choices=[
                        ui.choice(name="a", label="choice a"),
                        ui.choice(name="b", label="choice b"),
                        ui.choice(name="c", label="choice c"),
                    ],
                    values=["a"],
                ),
                ui.dropdown(
                    name='dp3',
                    label='dialog single',
                    choices=[
                        ui.choice(name="1", label="Choice 1"),
                        ui.choice(name="2", label="Choice 2"),
                        ui.choice(name="3", label="Choice 3"),
                    ],
                    popup="always",
                    value="1"
                ),
                ui.dropdown(
                    name='dp4',
                    label='dialog multi',
                    choices=[ui.choice(name=str(i), label=f'Choice {i}') for i in range(100000)],
                    values=["1"],
                    popup="always",
                ),
                ui.button(name="change", label="change"),
            ],
        )
    if q.args.change:
        q.page["example"].items[0].dropdown.value = 'b'
        q.page["example"].items[1].dropdown.values = ['b']
        q.page["example"].items[2].dropdown.value = '2'
        q.page["example"].items[3].dropdown.values = ['2']
        
    await q.page.save()
```

closes #1574

### CODE REVIEW

**Comment by mturoci** [comment]
Thanks for the great work @aalencar! I refactored your changes to make the components simpler. Please check the changes and apply additional refactors as we discussed.

**Comment by aalencar** [comment]
I didn't see any major performance improvement on using Map over a more functional style, recreating the array every time and setting `items` props as needed.

File: ui/src/dropdown.tsx [hunk 1]
```diff
@@ -118,12 +123,24 @@ const
...
         selection.clear()
-        setSelectedOptions([])
+        setMultiValues([])
         wave.args[name] = []
 
         onChange()
       }
 
+    React.useEffect(() => {
+      if (!isMultivalued) return
```
Comment (mturoci) [inline ui/src/dropdown.tsx:133]: Would this work if `isMultivalued` changes? It's not in the dep array. Checking `values` for `undefined` seems like a safer way here.

File: ui/src/dropdown.tsx [hunk 2]
```diff
@@ -118,12 +123,24 @@ const
...
+      setMultiValues(values || [])
+      wave.args[name] = values ?? null
+    }, [name, values])
+
+    React.useEffect(() => {
+      if (isMultivalued) return
```
Comment (mturoci) [inline ui/src/dropdown.tsx:139]: Same as above.

File: ui/src/dropdown.tsx [hunk 3]
```diff
@@ -152,119 +169,160 @@ const
...
+      : null,
 
-        if (values?.length) return values.map(v => itemsMap.get(v) || '').filter(Boolean).join(', ')
-        if (value) return itemsMap.get(value)
-      }),
-      toggleDialog = React.useCallback(() => setIsDialogHidden(!isDialogHidden), [isDialogHidden]),
-      cancelDialog = React.useCallback(() => {
+  DialogDropdownSingle = ({ model }: { model: Dropdown}) => {
+    const
+      { name, choices = [], disabled, required, trigger, placeholder, label } = model,
```
Comment (mturoci) [inline ui/src/dropdown.tsx:196]: nit: maybe we can use destructuring assignment for `value` here in the same way as in `BaseDropdown`?

File: ui/src/dropdown.tsx [hunk 4]
```diff
@@ -152,119 +169,160 @@ const
...
+            </Fluent.DialogContent>
+          </Fluent.Dialog>
+        </>
+      )
+  },
+  DialogDropdownMulti = ({ name, choices = [], values = [], disabled, required, trigger, placeholder, label }: Dropdown) => {
+    const
+      [isDialogHidden, setIsDialogHidden] = React.useState(true),
+      [items, setItems, onSearchChange] = useItems(choices, values),
+      auxItems = React.useRef([...items]),
```
Comment (mturoci) [inline ui/src/dropdown.tsx:249]: Wouldn't this be enough? Also naming needs work. Something like initial selection or something. Aux is too general.

```suggestion
      auxItems = React.useRef(items),
```

File: ui/src/dropdown.tsx [hunk 5]
```diff
@@ -152,119 +169,160 @@ const
...
+      openDialog = () => {
+        setIsDialogHidden(false)
+        auxItems.current = [...items]
```
Comment (mturoci) [inline ui/src/dropdown.tsx:252]: Same question as in initialization.

File: ui/src/dropdown.tsx (hunk 3 above)
Comment (mturoci) [reply ui/src/dropdown.tsx:196]: No, I am referering to 
image

if it can be the same as BaseDropdown - your most recent impl.

Screen Shot 2022-09-26 at 11 10 04 AM

File: ui/src/dropdown.tsx (hunk 4 above)
Comment (aalencar) [reply ui/src/dropdown.tsx:249]: > Wouldn't this be enough? 

It's enough because I am always creating a new array by using `map` in `setItems` and `auxItems`.
But semantically, `auxItems` is a copy so it makes sense to create a new array so that in the case someone (by mistake or not) mutates `items`, it won't be affected.

In terms of memory, I profiled `useRef(items)` and `useRef([...items])` and for some reason `useRef([...items])`  consistently performed slightly better. I don't know if using Chrome Devtools is enough to evaluate such a situation though.

3 and 7 are `useRef(items)` the rest is `useRef([...items])`.
image


>Also naming needs work. Something like initial selection or something. Aux is too general.

True. I'd not use `initialSelection` because it can imply that was it the first selection when the component was created. I'm going to use `itemsBackup` since it's used to revert to a previous state.

File: ui/src/dropdown.tsx (hunk 5 above)
Comment (aalencar) [reply ui/src/dropdown.tsx:252]: [Discussion here ](https://github.com/h2oai/wave/pull/1621#discussion_r979763603)

File: ui/src/dropdown.tsx (hunk 4 above)
Comment (mturoci) [reply ui/src/dropdown.tsx:249]: > so that in the case someone (by mistake or not) mutates items, it won't be affected.

This is a shallow copy, not a deep copy so this doesn't hold true - it should be affected in both scenarios.

> I don't know if using Chrome Devtools is enough to evaluate such a situation though.

AFAIK it should allow you to explore the complete memory snapshot item by item so you can see what's the root cause of the extra memory.

> it can imply that was it the first selection when the component was created. I'm going to use itemsBackup since it's used to revert to a previous state

What is previous state in this case? I thought it's the initial selection that is seen after opening the dialog, but maybe I am wrong?

File: ui/src/dropdown.tsx (hunk 1 above)
Comment (aalencar) [reply ui/src/dropdown.tsx:133]: TBH, I was not even considering that we want to allow to dynamically switch between single and multi, but it worked by simply adding `isMultivalued` to dep array. One caveat: `values` needs to be set to `None` to switch from multi to single.

Repro code

```py
from h2o_wave import app, main, Q, ui


@app("/demo")
async def serve(q: Q) -> None:
    if not q.client.initialized:
        q.client.initialized = True
        q.page["example"] = ui.form_card(
            box="1 1 4 6",
            items=[
                ui.dropdown(
                    name='dropdown',
                    label='dropdown',
                    choices=[
                        ui.choice(name="1", label="Choice 1"),
                        ui.choice(name="2", label="Choice 2"),
                        ui.choice(name="3", label="Choice 3"),
                    ],
                    value="1",
                ),
                ui.button(name="single", label="single (value = 2)"),
                ui.button(name="multi", label="multi (values = [2, 3])"),
                ui.button(name="popup_on", label="popup on"),
                ui.button(name="popup_off", label="popup off"),
            ],
        )
    if q.args.single:
        q.page["example"].items[0].dropdown.value = '2'
        q.page["example"].items[0].dropdown.values = None
    if q.args.multi:
        q.page["example"].items[0].dropdown.values = ['2', '3']
    if q.args.popup_on:
        q.page["example"].items[0].dropdown.popup = 'always'
    if q.args.popup_off:
        q.page["example"].items[0].dropdown.popup = 'never'

    await q.page.save()

```

Also, checked whether changing `popup` dynamically it would work but found some bugs.

**Comment by aalencar** [comment]
> The only thing that bothers me is a lot of introduced duplication, especially in the markup part, but we can leave that for future.

It also bothered me. As you said, we can leave it for another moment.

File: ui/src/dropdown.tsx (hunk 3 above)
Comment (mturoci) [reply ui/src/dropdown.tsx:196]: I see, thanks for clarification.

File: ui/src/dropdown.tsx (hunk 4 above)
Comment (aalencar) [reply ui/src/dropdown.tsx]: > This is a shallow copy, not a deep copy so this doesn't hold true - it should be affected in both scenarios.

Good point, I overlooked that. I guess we can simply pass the `items` reference.

> AFAIK it should allow you to explore the complete memory snapshot item by item so you can see what's the root cause of the extra memory.

If I wanted a detailed explanation, yes, but in this case, I just want to see the overall change to memory since the only thing changed in my code was `useRef([...items])` -> `useRef(items)`. I'm not very familiar with the profiler tool though.

> What is previous state in this case? I thought it's the initial selection that is seen after opening the dialog, but maybe I am wrong?

You are right, you are saying that it's "initial" at the moment we open the dialog. I'm saying that the word "initial" can also mean "when the component is initialized and these values will not change" and that can be confusing. Maybe rename to `snapshot`?
I believe that anyone will be able to follow the logic anyway. I'm fine with `initialSelection` as well.

Comment (mturoci) [reply ui/src/dropdown.tsx]: >  just want to see the overall change to memory since the only thing changed in my code was useRef([...items]) -> useRef(items)

I see. I was just wondering about the cause because IMO it should be the other way around - using reference should result in less memory.

> when the component is initialized and these values will not change" and that can be confusing

Got it. `snapshot` is still too broad. Maybe something in the lines of `itemsOnOpen` / `snapshotOnOpen` or maybe even `onDialogOpen` which is the most crystal clear possible probably :D

Comment (aalencar) [reply ui/src/dropdown.tsx]: `onDialogOpen` sounds like an event handler. I went with `itemsOnDialogOpen`.

File: ui/src/dropdown.tsx (hunk 3 above)
Comment (aalencar) [reply ui/src/dropdown.tsx:196]: No problem.

**Review by mturoci — APPROVED** [review]
Thanks @aalencar!
