### PR TITLE
fix: Trigger multi combobox args after they are set, not before.

### LINKED ISSUE #2342: New values in ui.combobox trigger a button submission
#### Wave SDK Version, OS

h2o-wave 1.2.0

#### Actual behavior

Minimum code example:

```python
from h2o_wave import Q, app, main, ui


@app("/")
async def serve(q: Q):
    print(q.args)
    q.page['example'] = ui.form_card(box='1 1 2 2', items=[
        ui.combobox(
            name="my_coolest_combobox",
            label="Selection",
            values=["choice1"],
            required=False,
            choices=["choice1", "choice2"],
            trigger=True,
        ),
        ui.button(
            name="i_am_a_button",
            label=(
                "Don't click me"
            ),
            primary=True,
        )
    ])
    await q.page.save()
```

When adding a new value to the combobox, I am getting: 
`q.args: __wave_submission_name__:'i_am_a_button'`

When selecting an existing value in the combobox, I am getting: 
`q.args: __wave_submission_name__:'my_coolest_combobox'`

#### Expected behavior

In both cases, I would expect the `__wave_submission_name__` to be `'my_coolest_combobox'``

#### Steps To Reproduce

1. Use minimum code example above
2. Add an new value to the combobox and wait for the trigger
3. Select a value from the combobox and wait for the trigger
4. Compare q.args prints in the console

### PR DESCRIPTION
**Pull request by mturoci**
Closes #2342

### CODE REVIEW

File: ui/src/combobox.tsx [hunk 1]
```diff
@@ -110,22 +111,23 @@ const ComboboxMultiSelect = ({ model: m }: { model: Omit<Combobox, 'value'> }) =
...
-        return result
+      flushSync(() => {
+        setSelected(keys => {
+          const result = option.selected ? [...keys, String(option.key)] : keys.filter(key => key !== option.key)
+          wave.args[m.name] = result
+          return result
+        })
       })
+
+      if (m.trigger) wave.push()
```
Comment (marek-mihok) [inline ui/src/combobox.tsx:122]: Can using the `flushSync` be avoided? This should be enough:
```suggestion
      const result = option.selected ? [...selected, String(option.key)] : selected.filter(key => key !== option.key)
      setSelected(result)
      wave.args[m.name] = result
      if (m.trigger) wave.push()
```

**Review by marek-mihok — CHANGES_REQUESTED** [review]
Good job @mturoci! Everything is working as expected. Just one minor thing - using `flushSync` [can be risky](https://react.dev/reference/react-dom/flushSync) and it is a last resort solution. In this case I think we could go without it (see the suggestion).

File: ui/src/combobox.tsx (hunk 1 above)
Comment (mturoci) [reply ui/src/combobox.tsx:122]: Our `selected` state depends on its prev state thus a callback is necessary to make it safe.

flushSync is not risky, it just avoids batching state updates, but since we need to know the prev state, we do want sync updates anyway.

Comment (mturoci) [reply ui/src/combobox.tsx:122]: Using your suggestion should work as well, but there are no guarantees from React that each user event like blur, tab, enter etc. commit state so I prefer to not depend on the internal implementation, especially when we are in the maintenance mode and I want each of us to spend at little time on this project as possible.

Comment (marek-mihok) [reply ui/src/combobox.tsx:122]: Thanks for clarification! Your points make sense.
