### PR TITLE
fix: Make disabled ui.button icon and text colours consistent #1664

### LINKED ISSUE #1664: Button icon contrast is inconsistent
#### Wave SDK Version, OS
v0.23.1 on MacOS

#### Actual behaviour
Default theme:
Screenshot 2022-10-08 at 4 10 34 PM

Dark theme:
Screenshot 2022-10-08 at 4 10 50 PM

1st button: Disabled, Not Primary
2nd button: Not Disabled, Not Primary
3rd button: Disabled, Primary
4th button: Not Disabled, Primary

#### Expected behaviour
(Unless there's some trickery that my eye is missing) It seems the 1st, 2nd & 4th buttons have the icon and text using the same colour but the 3rd button has the icon and text in different colour contrasts, irrespective of the theme.

#### Comments
Maybe related to https://github.com/h2oai/wave/issues/791

### PR DESCRIPTION
**Pull request by marek-mihok**
This PR provides an override of icon colour for all disabled FluentUI buttons.

https://user-images.githubusercontent.com/23740173/203029158-a6c771f6-5731-4253-9a94-8a953f300aad.mov

Closes #1664

### CODE REVIEW

**Review by mturoci — CHANGES_REQUESTED** [review]
Thanks @marek-mihok, we should ideally fix this globally for every Fluent button component (e.g. we use buttons for pagination in table etc.).

File: ui/src/app.tsx [hunk 1]
```diff
@@ -116,7 +128,7 @@ const
                 const page = e.page
                 const lightbox = lightboxB()
                 return (
-                  <Fluent.ThemeProvider>
+                  <Fluent.ThemeProvider theme={{ components: componentCustomStyles }}>
```
Comment (mturoci) [inline ui/src/app.tsx:131]: Use a file-scoped const instead to improve perf as suggested in Fluent docs:

image

**Review by mturoci — CHANGES_REQUESTED** [review]

File: ui/src/app.tsx (hunk 1 above)
Comment (marek-mihok) [reply ui/src/app.tsx]: I've first moved the constant `componentCustomStyles`  from inside `bond()` to the upper scope, but now I see I should move also whole `{components: componentCustomStyles}` object. 
Thank you @mturoci , now it should be correct.

**Review by mturoci — APPROVED** [review]
Thanks @marek-mihok!
