### PR TITLE
fix: Make ui.notification_bar to overlay the ui.side_panel

### LINKED ISSUE #1764: Notification bar isn't visible over the side panel
#### Wave SDK Version, OS

Wave SDK: 0.24.1, Wave Daemon: 0.24.1, OS: MacOs

#### Actual behavior

Notification bar is not appeared over the side panel when the side panel is active. Only can see after side panel is closed.  

https://user-images.githubusercontent.com/12801761/207850330-e6533b71-3195-4bf3-a3f8-7ce912974f45.mov

#### Expected behavior

It's required to show notification bar over the side panel. 

Screenshot 2022-12-15 at 17 08 03

#### Steps To Reproduce

You can run the following code to create the issue:

```py
@app('/')
async def serve(q: Q):
    if not q.client.initialized:
        # Create an empty meta_card to hold the notification bar
        q.page['meta'] = ui.meta_card(box='')
        # Display a button to show the notification bar
        q.page['form'] = ui.form_card(box='1 1 2 4', items=[
            ui.button(name="show_side_panel", label="Show side panel")
        ])
        q.client.initialized = True

    # Was the show_notification_bar button clicked?
    if q.args.show_notification_bar:
        # Create a notification bar
        q.page['meta'].notification_bar=ui.notification_bar(
            text='You can close me!',
            name="my_bar",
            # Get notified when the notification bar is dismissed.
            events=['dismissed'],
        )
    if q.args.show_side_panel:
        q.page["meta"].side_panel = ui.side_panel(
        title="",
        items=[ui.text("Side panel text"), ui.button(name='show_notification_bar', label='Show notification bar')],
        name="side_panel",
        events=["dismissed"],
        closable=True,
    )

    # Did we get events from the notification bar?
    if q.events.my_bar:
        # Was the notification bar dismissed?
        print("events triggered")
        if q.events.my_bar.dismissed:
            # Delete the notification bar
            print("dismissed")
            q.page['meta'].notification_bar = None

    if q.events.side_panel:
        if q.events.side_panel.dismissed:
            print("side panel dismissed")
            q.page["meta"].side_panel = None

    await q.page.save()
```

### PR DESCRIPTION
**Pull request by marek-mihok**
https://user-images.githubusercontent.com/23740173/214858284-d6bbddff-a40b-4e31-ba94-1c035b6134e2.mov

Closes #1764

### CODE REVIEW

File: ui/src/notification_bar.tsx [hunk 1]
```diff
@@ -94,7 +94,7 @@ export const
           buttons = currentModel?.buttons?.filter(({ button }) => button),
           isMultiline = isMessagebarMultiline(currentModel?.text, buttons)
 
-        if (model?.timeout !== -1 && shouldBeOpen) timeout = window.setTimeout(onDismiss, (model?.timeout || 5) * 1000)
+        if (model?.timeout !== -1 && shouldBeOpen) timeout = window.setTimeout(onDismiss, (model?.timeout || 5000) * 1000)
```
Comment (mturoci) [inline ui/src/notification_bar.tsx:97]: Leftover probably?

Comment (marek-mihok) [reply ui/src/notification_bar.tsx]: Exactly. Leftover from debugging.

**Review by mturoci — APPROVED** [review]
LGTM!
