### PR TITLE
Fix ProgressArc in Safari

### LINKED ISSUE #520: Tall gauge stat not working in Safari
image

### PR DESCRIPTION
**Pull request by mturoci**
`height: 100%` is not working for flex parent with `flex-grow: 1`. Had to use absolute positioning instead.

Closes #520

### CODE REVIEW

File: ui/src/parts/progress_arc.tsx [hunk 1]
```diff
@@ -29,7 +29,9 @@ const css = stylesheet({
   container: {
     width: '100%',
     height: '100%',
-    position: 'relative',
+    // Height 100% is not working in Safari. Without this, container has 0 height and d3 cannot compute properly.
```
Comment (lo5) [inline ui/src/parts/progress_arc.tsx:32]: Maybe we should get rid of the 100% width/height?

Comment (mturoci) [reply ui/src/parts/progress_arc.tsx:30]: Good catch!

**Review by lo5 — APPROVED** [review]
Thanks @mturoci!
