### PR TITLE
fix: Prevent copy button from overlapping multiline labels in ui.copyable_text

### LINKED ISSUE #1883: Copy to clipboard button of copyable_text renders wrongly when label wraps.
image

## Repro

```py

# Form / Copyable Text
# Use copyable text component to enable user quick text copy pasting.
# #copyable_text
# ---
from h2o_wave import site, ui


multiline_content = '''Wave is truly awesome.
You should try all the features!'''
big_multiline_content = '''Wave is truly awesome.
You should try all the features!
Like having a big height textbox!
...
...
...
...
Woohoo!'''
page = site['/demo']

page['hello'] = ui.form_card(box='1 1 2 6', items=[
    ui.copyable_text(label='Copyable text', value='Hello world!'),
    ui.copyable_text(label='Multiline Copyable text', value=multiline_content, multiline=True),
    ui.copyable_text(label='Multiline Copyable text with height=200px', value=big_multiline_content, multiline=True, height='200px'),
])

page.save()

```

### PR DESCRIPTION
**Pull request by marek-mihok**
This PR positions the copy button relative to label container instead of the textfield component. By this change the button is not overlapping the text in case of multiline labels.

image

Closes #1883

### CODE REVIEW

File: ui/src/copyable_text.tsx [hunk 1]
```diff
@@ -88,30 +92,34 @@ export const XCopyableText = ({ model }: { model: CopyableText }) => {
...
-      <Fluent.PrimaryButton
-        title='Copy to clipboard'
-        onClick={onClick}
-        iconProps={{ iconName: copied ? 'CheckMark' : 'Copy' }}
-        className={clas(css.btn, copied ? css.copiedBtn : '', multiline ? css.btnMultiline : '')}
-      />
-    </div>
+      componentRef={ref}
+      value={value}
+      label={label}
```
Comment (mturoci) [inline ui/src/copyable_text.tsx:99]: Probably not necessary in favor of `onRenderLabel`.
```suggestion
```

File: ui/src/copyable_text.tsx [hunk 2]
```diff
@@ -88,30 +92,34 @@ export const XCopyableText = ({ model }: { model: CopyableText }) => {
...
+            iconProps={{ iconName: copied ? 'CheckMark' : 'Copy' }}
+            className={clas(css.btn, copied ? css.copiedBtn : '', multiline ? css.btnMultiline : '')}
+          />
+        </div>
+      }
+      styles={{
+        root: {
+          ...heightStyle,
+          ...styles.textFieldRoot,
+          ...multiline ? styles.textFieldMultiline : undefined
```
Comment (mturoci) [inline ui/src/copyable_text.tsx:116]: Any particular reason for not inlining this?
```suggestion
          textFieldRoot: { position: 'relative', width: pc(100) },
          textFieldMultiline: multiline ? { '&:hover button': { opacity: 1 } } : undefined
```

**Review by mturoci — CHANGES_REQUESTED** [review]
Thanks @marek-mihok. LGTM, just 2 small comments.

File: ui/src/copyable_text.tsx (hunk 1 above)
Comment (marek-mihok) [reply ui/src/copyable_text.tsx:99]: Good point!

File: ui/src/copyable_text.tsx (hunk 2 above)
Comment (marek-mihok) [reply ui/src/copyable_text.tsx:116]: There is not. I try to prevent inlining styles whenever not necessary. But I agree this time the readability is better when inlined.

**Review by mturoci — APPROVED** [review]
